### ISSUE TITLE
Best way to update my blog using middleman-casper?

### ISSUE THREAD

**Issue by douglascamata** [danielbayerlein/middleman-casper#10]
I started a blog using this awesome template and did some small customisations. What is the best way to try to "merge" them with upstream?

**Comment by danielbayerlein** [comment]
@tdreyno Do you have a recommendation on how to update a middleman template?

**Comment by tdreyno** [comment]
I think @douglascamata would submit either a PR to this repo, if the changes are MM related, or all the wait upstream to Casper if they are changes to that system.

@douglascamata You'd have to edit the files from a fork of this repo, then submit the changes.

**Comment by douglascamata** [comment]
@tdreyno I think I was not clear in my question. Let's say I start a project using this theme. In a few months or so, the theme will be updated by @danielbayerlein and my blog will be using an outdated version of the theme.

What is the best to keep my blog's theme up to date with this repository?

**Comment by tdreyno** [comment]
Seems like the core of this template is just a casper.css and a casper.js, I'd update those manually to the current versions as you see fit.

**Comment by danielbayerlein** [comment]
@douglascamata 

One option is to use the comparison function.
* https://github.com/danielbayerlein/middleman-casper/compare.

With Git it should also work, if you are familiar with it:
* http://stackoverflow.com/questions/8929071/merging-git-repositories-at-different-directory-levels
* http://stackoverflow.com/questions/1214906/how-do-i-merge-a-sub-directory-in-git
* http://stackoverflow.com/questions/22582605/git-merge-branches-with-different-directory-structures

I would appreciate any feedback.
