### ISSUE TITLE
How do I update this theme in my project?

### ISSUE THREAD

**Issue by ylluminarious** [danielbayerlein/middleman-casper#14]
I installed this theme a while back and now I would like to update it. I don't see any documentation on how to do so here or on Middleman's website. I would very much prefer not to have to create a new project directory from scratch.

**Comment by ylluminarious** [comment]
Okay, so I guess all I had to do was run this incantation on my existing project directory:
```sh
$ middleman init -T danielbayerlein/middleman-casper MY_PROJECT_FOLDER # This folder should already exist
```
And then I just answered which files I wanted to overwrite. I was only prompted for conflicting files, like `config.rb` and my stylesheets. **I'd suggest having a backup of your folder _before_** running the above command. You can either make a copy of your project directory or use version control. This certainly doesn't seem like the cleanest solution, but it worked so there you have it.

**Comment by danielbayerlein** [comment]
See https://github.com/danielbayerlein/middleman-casper/issues/10#issuecomment-228590200
