### ISSUE TITLE
Upgrading to Middleman v4

### ISSUE THREAD

**Issue by danielbayerlein** [danielbayerlein/middleman-casper#4]
[Upgrading to v4](https://middlemanapp.com/basics/upgrade-v4/)

**Comment by lbischof** [comment]
What's the status on this?

**Comment by danielbayerlein** [comment]
@lbischof middleman(-blog) v4 is not yet published.

**Comment by lbischof** [comment]
Middleman v4 was published 6 days ago. I would really love to use this awesome theme. Thanks for porting it.

**Comment by douglascamata** [comment]
@danielbayerlein middleman-blog v4 is on Ruby Gems since since December 16: https://rubygems.org/gems/middleman-blog.

**Comment by danielbayerlein** [comment]
@douglascamata I know, but the upgrade is not easy ... Please have a little patience.

**Comment by douglascamata** [comment]
@danielbayerlein ok ok, I was just pinging... no rush. :P

**Comment by danielbayerlein** [comment]
@douglascamata :v:

**Comment by danielbayerlein** [comment]
Feedback is welcome!

```bash
$ middleman init -T "danielbayerlein/middleman-casper#4.0" MY_PROJECT_FOLDER
```

/cc @douglascamata, @lbischof

**Comment by danielbayerlein** [comment]
Done! :tada:

**Comment by lbischof** [comment]
Thanks very much. I'm currently working on another project, but will try it when I have time.

**Comment by douglascamata** [comment]
@danielbayerlein im going to try in the following days too. I had some small modifications in the template files and css, do you have any tips for the upgrade?

**Comment by danielbayerlein** [comment]
@douglascamata I think the easiest way is if you use `diff`.
