### ISSUE TITLE
horizontally long code doesn't fit in nicely

### ISSUE THREAD

**Issue by kjtanaka** [danielbayerlein/middleman-casper#6]
Thanks for sharing a nice template, but I'm having an issue that horizontally long code doesn't fit in nicely. Like the following code, for example, should have a horizontal scroll bar, but it's not on your template.

```
git clone https://github.com/danielbayerlein/middleman-casper.git ~/.middleman/casper #  horizontally long code goes beyond the box without being able to scroll
```

I guess the following lines should fix this issue, but I don't know where to put these lines. I tried it in `pre`, but didn't work as I hoped.

```
white-space:pre-wrap;
overflow-x:scroll;
overflow-y:hidden;
``` 

Thanks,

**Comment by danielbayerlein** [comment]
@kjtanaka Thank you for the reporting. I will check the problem as soon as possible.

**Comment by danielbayerlein** [comment]
Have a look at 12a31b6397929eecc2a2f5aabbb785810b154d29 - please update the theme.

**Comment by kjtanaka** [comment]
@danielbayerlein It works now:) Thanks a lot for the fix!

**Comment by danielbayerlein** [comment]
You're welcome! :smiley:
