### ISSUE TITLE
Creating a gem

### ISSUE THREAD

**Issue by sunnyrjuneja** [danielbayerlein/middleman-casper#7]
First, thank you so much for your hard work. I really appreciate it.

I was wondering if you would consider package this up as a gem which would make the installation/upgrading process a bit simpler. Maybe similar to [middleman-blog](https://github.com/middleman/middleman-blog).

**Comment by danielbayerlein** [comment]
middleman-casper is now following the official "Custom Templates" instructions: https://middlemanapp.com/advanced/custom-templates/

**Comment by sunnyrjuneja** [comment]
Thanks! :)
