### ISSUE TITLE
`tag` local conflicts with `tag` helper

### ISSUE THREAD

**Issue by tdreyno** [danielbayerlein/middleman-casper#9]
Good morning,

So in the next Middleman release, we're raising an error when a local value tries to overwrite a template helper. In your template, you pass the `tag:` local, but in Padrino there is a `tag` helper for generating HTML.

This is just a heads up, if you rename that local, you'll be compatible with our upcoming release (and no longer accidentally removing access to the tag HTML helper) :)

**Comment by danielbayerlein** [comment]
Hi @tdreyno,

thank you for the info! I'll fix it ASAP. 😃

**Comment by danielbayerlein** [comment]
Done 😉
